# Generated by Django 6.0.7 on 2026-07-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_product_alter_payment_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transaction_type',
            field=models.CharField(choices=[('membership', 'Membership'), ('product', 'Product')], default='membership', max_length=20),
        ),
    ]
