# Generated by Django 6.0.8 on 2026-09-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_emailnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
    ]
