# Generated by Django 6.0.8 on 2026-09-18 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, default='', help_text='International phone format e.g. +919876543210 or +14155552671', max_length=25),
        ),
        migrations.AddField(
            model_name='profile',
            name='sms_alerts_enabled',
            field=models.BooleanField(default=True, help_text='Receive transactional SMS notifications'),
        ),
        migrations.AddField(
            model_name='profile',
            name='whatsapp_alerts_enabled',
            field=models.BooleanField(default=True, help_text='Receive WhatsApp notifications and invoice updates'),
        ),
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='whatsapp', max_length=20)),
                ('recipient_phone', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('sent', 'Sent (Live API)'), ('simulated', 'Simulated (Sandbox/Log)'), ('failed', 'Failed')], default='simulated', max_length=20)),
                ('provider', models.CharField(default='Twilio / Gupshup', max_length=50)),
                ('response_payload', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
